# Generated by Django 5.2.1 on 2025-05-14 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('sports', 'Sports'), ('music', 'Music'), ('reading', 'Reading'), ('tech', 'Tech')], default='everyone', max_length=10),
        ),
    ]
